name: Build GBA ROM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache devkitPro
        id: cache-devkitpro
        uses: actions/cache@v4
        with:
          path: /opt/devkitpro
          key: ${{ runner.os }}-devkitpro

      - name: Install devkitPro
        if: steps.cache-devkitpro.outputs.cache-hit != 'true'
        run: |
          wget https://apt.devkitpro.org/install-devkitpro
          chmod +x ./install-devkitpro
          sudo ./install-devkitpro
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S gba-dev --noconfirm

      - name: Add devkitPro to PATH
        run: echo "/opt/devkitpro/tools/bin" >> $GITHUB_PATH

      - name: Run make
        run: make
        env:
          DEVKITPRO: /opt/devkitpro

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: gba-portfolio-rom
          path: GBA-Portfolio.gba